/*
 * MUART_Config.h
 *
 *  Created on: Nov 25, 2021
 *      Author: Mina-Ryad
 */

#ifndef MCAL_MUART_MUART_CONFIG_H_
#define MCAL_MUART_MUART_CONFIG_H_

/* UART Mode Options:
 * 1- UART_ASYNCHRONOUS_MODE
 * 2- UART_SYNCHRONOUS_MODE
 * */
#define UART_SET_MODE  UART_ASYNCHRONOUS_MODE

/* UART Parity mode options:
 * 1- UART_PARITY_MODE_DISABELED
 * 2- UART_PARITY_MODE_EVEN
 * 3- UART_PARITY_MODE_ODD
 * */
#define UART_SET_PARITY_MODE UART_PARITY_MODE_DISABELED

/* UART Stop mode options:
 * 1- UART_STOP_ONE_BIT
 * 2- UART_STOP_TWO_BIT
 * */
#define UART_STOP_BIT UART_STOP_ONE_BIT

/* UART Char Size
 * 1- UART_CHAR_SIZE_5
 * 2- UART_CHAR_SIZE_6
 * 3- UART_CHAR_SIZE_7
 * 4- UART_CHAR_SIZE_8
 * 5- UART_CHAR_SIZE_9
 *  */
#define UART_SET_CHAR_SIZE UART_CHAR_SIZE_8

/*RX Complete Interrupt options:
 * 1- RX_INTERRUPT_ENABLED
 * 2- RX_INTERRUPT_DISABELED
 * */
#define RX_INTERRUPT  RX_INTERRUPT_DISABELED

/*TX Complete Interrupt options:
 * 1- TX_INTERRUPT_ENABLED
 * 2- TX_INTERRUPT_DISABELED
 * */
#define TX_INTERRUPT  TX_INTERRUPT_DISABELED

/*TX Complete Interrupt options:
 * 1- UDR_INTERRUPT_ENABLED
 * 2- UDR_INTERRUPT_DISABELED
 * */
#define UDR_INTERRUPT  UDR_INTERRUPT_ENABLED


#endif /* MCAL_MUART_MUART_CONFIG_H_ */
