/*
 * MEXTI_Config.h
 *
 *  Created on: Nov 15, 2021
 *      Author: Mina-Ryad
 */

#ifndef MCAL_MEXTI_MEXTI_CONFIG_H_
#define MCAL_MEXTI_MEXTI_CONFIG_H_


/* Sense Control Options:
 * 1- MEXTI_LOW_LEVEL
 * 2- MEXTI_ANY_LOGICAL_CHANGE
 * 3- MEXTI_FALLING_EDGE
 * 4- MEXTI_RISING_EDGE
*/
#define MEXTI0_SET_SENSE_CONTROL MEXTI_FALLING_EDGE
#define MEXTI1_SET_SENSE_CONTROL MEXTI_FALLING_EDGE
#define MEXTI2_SET_SENSE_CONTROL MEXTI_FALLING_EDGE

#endif /* MCAL_MEXTI_MEXTI_CONFIG_H_ */
