/*
 * MADC_Config.h
 *
 *  Created on: Nov 22, 2021
 *      Author: Mina-Ryad
 */

#ifndef MCAL_MADC_MADC_CONFIG_H_
#define MCAL_MADC_MADC_CONFIG_H_


/* MADC Reference Voltage Options:
 * 1- MADC_AVCC_REFERENCE_VOLTAGE
 * 2- MADC_2.56_REFERENCE_VOLTAGE
 * */
#define MADC_SET_REFERANCE_VOLTAGE 		MADC_AVCC_REFERENCE_VOLTAGE

/* MADC Prescaler Options:
 * 1- MADC_2_PRESCALER
 * 2- MADC_4_PRESCALER
 * 3- MADC_8_PRESCALER
 * 4- MADC_16_PRESCALER
 * 5- MADC_32_PRESCALER
 * 6- MADC_64_PRESCALER
 * 7- MADC_128_PRESCALER
 * */
#define MADC_SET_PRESCALER		MADC_8_PRESCALER

#define CHANNEL_0	0
#define CHANNEL_1	1
#define CHANNEL_2	2
#define CHANNEL_3	4
#define CHANNEL_5	5
#define CHANNEL_6	6
#define CHANNEL_7	7


/* ADC Adjust Options:
 * 1- MADC_LEFT_ADJUST
 * 2- MADC_RIGHT_ADJUST
*/
#define MADC_SET_ADJUST		MADC_RIGHT_ADJUST

/*ADC Interrupt Enable
 * 1- MADC_INTERRUPT_DISABLE
 * 2- MADC_INTERRUPT_ENABLE
 * */
#define MADC_INTERRUPT		MADC_INTERRUPT_ENABLE

/* ADC Auto Trigger Source options:
 * 1- FREE_RUNNUNG_MODE
 * 2- ANALOG_COMPARATOR
 * 3- EXTERNAL_INTERRUPT_0
 * 4- TIMER_0_CTC
 * 5- TIMER_0_OVERFLOW
 * 6- TIMER_1_CTC_B
 * 7- TIMER_1_OVERFLOW
 * 8- TIMER_1_ICU
 * */

#define MADC_AUTO_TRIGGER_MODE 		FREE_RUNNUNG_MODE


#define MADC_AUTO_TRIGGER 		 MADC_AUTO_TRIGGER_ENABLE


#endif /* MCAL_MADC_MADC_CONFIG_H_ */
